[project]
name = "heif2png"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow-heif>=0.22.0",
    "pyinstaller>=6.13.0",
    "pyqt6>=6.9.0",
]
